version: "3.9"

services:
  app:
    build: .
    container_name: bookshelf-app
    ports:
      - "8080:8080"
    environment:
      HTTP_PORT: "8080"
      DB_DSN: postgres://postgres:postgres@db:5432/bookshelf?sslmode=disable
    depends_on:
      - db      
  

  db:
    image: postgres:16
    container_name: bookshelf-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
